version: '3.8'

services:
  go-react-blog-backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: go-react-blog-db
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - go-react-blog-db

  go-react-blog-db:
    image: postgres:14.7
    build: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
